name: MirageIslands
version: '1.0'
main: com.nensi.mirageislands.MirageIslands
api-version: '1.20'
commands:
  mirageislands:
    usage: /mirageislands

softdepend:
  - ProtocolLib
  - WorldEdit
  - ItemsAdder
